language: java
jdk:
- openjdk8
before_deploy:
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: target/connect-four-challenge-server-1.0-SNAPSHOT.zip
  skip_cleanup: true
  on:
    repo: lakermann/connect-four-challenge-server
